const CollectionsActionTypes = {
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
  FETCH_COLLECTIONS_OFFLINE: 'FETCH_COLLECTIONS_OFFLINE',
  FETCH_QUERY_START: 'FETCH_QUERY_START',
  FETCH_QUERY_SUCCESS: 'FETCH_QUERY_SUCCESS',
  FETCH_QUERY_FAILURE: 'FETCH_QUERY_FAILURE',
};

export default CollectionsActionTypes;